### ISSUE TITLE
UV problems on import

### ISSUE THREAD

**Issue by astandarduser** [julienduroure/gltf2-blender-importer#26] opened 2019-01-01 02:05 UTC
I notice when I import glb files using blender 2.8, the UV's are not in the main UV space, and are far too big in scale, so the textures don't assign correctly

**Comment by julienduroure** [comment] 2019-01-01 19:52
Can you please provide:
- What exact version of blender and what addon you are using, and addon version. You are reporting here on this repository, but this version is not ported to 2.80, so you can't use this addon.
- A glb or gltf file to reproduce your issue.

Thanks

**Comment by astandarduser** [comment] 2019-01-05 00:48
I sent you an email, it was a glb file. I didn't attach the file for a reason, and I just based what I said on this "If you are using Blender 2.8, addon is activated by default, you don't need to install or activate anything.". It would also be nice to know if there is a way to impot multiple glb files at once using the 2.8 addon, because it doesn't appear to at the moment. Thanks for the response

**Comment by julienduroure** [comment] 2019-01-05 07:54
* You are using 2.8, so I will transfer this issue to right issue tracker
* Your archive contains 14 different glb files! Please tell us what file has problem
* None of these files has some materials (no "material" in json), so you can't see any materials
* Seems Facebook does not use glb in standard way
* UV seems to be strange --> Will have a look on it

**Comment by julienduroure** [comment] 2019-01-06 17:04
Fixed on glTF-Blender-IO repository

**Closed as completed by julienduroure** 2019-01-06 17:04 UTC
